# .github/labeler.yml
"area:engine":
  - changed-files:
    - any-glob-to-any-file: "engine/**/*"

"area:ui":
  - changed-files:
    - any-glob-to-any-file: "ui/**/*"

"area:tests":
  - changed-files:
    - any-glob-to-any-file: "tests/**/*"

"area:deployment":
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**/*"
    - any-glob-to-any-file: "Dockerfile"
    - any-glob-to-any-file: "azure*"

"dependencies":
  - changed-files:
    - any-glob-to-any-file: "requirements.txt"
  - title: "^(build|chore|deps)(\\([a-z-]+\\))?:"

"documentation":
  - changed-files:
    - any-glob-to-any-file: "*.md"

"config":
  - changed-files:
    - any-glob-to-any-file: "*.yml"
    - any-glob-to-any-file: "*.yaml"
    - any-glob-to-any-file: ".github/**/*"

"bug":
  - title: "^(fix|bugfix)(\\([a-z-]+\\))?:"
"enhancement":
  - title: "^(feat|feature|enhancement)(\\([a-z-]+\\))?:"
"chore":
  - title: "^chore(\\([a-z-]+\\))?:"
